Задча инсталлировать magento:         (см. файл: install_Magento_browser_part.docx - в картинках )

  проект называется:  D:\pro\ol.mce\
  база данных:        mce


1. D:\install\xampp\magento\magento_install\CE\magento-1.7.0.2\magento\*.* ----> D:\pro\ol.mce\*.*
   (скоприровать)
   + создать D:\pro\ol.mce\logs\
   
2. в файл C:\Windows\System32\drivers\etc\hosts добавить строки
...
127.0.0.1 ol.mce
127.0.0.1 www.ol.mce

3. отконфигурировать виртуальных хост
   C:\xampp\apache\conf\extra\httpd-vhosts.conf
...
<VirtualHost *:80>
    ServerAdmin admin@ol.mce
    DocumentRoot "D:\pro\ol.mce"
    ServerName ol.mce
    ServerAlias www.ol.mce
    ErrorLog "D:\pro\ol.mce\logs\error.log"
    CustomLog "D:\pro\ol.mce\logs\access.log" common
    <Directory "D:\pro\ol.mce">
      Options Indexes FollowSymLinks Includes ExecCGI
      AllowOverride All
      Require all granted
    </Directory>
</VirtualHost>
   
4. Создать базу данных mce.
   a. "C:\Program Files (x86)\PremiumSoft\Navicat Premium\navicat.exe"
       connections 
           (rootConnection) - это имя моего коннекта
              правая кнопка мыши, "New Database"
                    Database Name : mce
		    Character set :
		        Collation :

                        "OK"
   б. 
      C:\xampp\mysql\bin\mysql -u root
      mysql> create database mce;             где: mce - имя базы данных

      команды: 
      mysql> show databases;
      mysql> use db_name;
      mysql> show tables;
      mysql quit;


5.  Если не создана директория D:\pro\ol.mce\logs\, создать!!
    Запустить XAMPP Control Panel
    в инет-браузере ввести: www.ol.mce/
    начнётся инсталляция.
    отвечать на все вопросы.
    если не возникнет проблем - это всё.

    во время инсталяции все имена были ol
    почта: gololol@ukr.net
    для базы данных пользователь: root


6. может возникнуть проблема. 
    На третьем шаге "Connection to DB" или как-то по дургому называется.
    Возникает сообщение: "Database server does not support the InnoDB storage engine.".

    Решение проблемы 
    D:\pro\ol.mce\app\code\core\Mage\Install\Model\Installer\Db.php копировать
    в D:\pro\ol.mce\app\code\local\Mage\Install\Model\Installer\
    (если дир-ии local не будет, то её создать)

    Файл D:\pro\ol.mce\app\code\local\Mage\Install\Model\Installer\Db.php
    отредактировать
       Было
            // check InnoDB support
            if (!$resource->supportEngine()) {
                Mage::throwException(
                    Mage::helper('install')->__('Database server does not support the InnoDB storage engine.')
                );
            }
       Стало
            // // check InnoDB support
            // if (!$resource->supportEngine()) {
            //     Mage::throwException(
            //         Mage::helper('install')->__('Database server does not support the InnoDB storage engine.')
            //     );
            // }

	    
       после инсталляции удалить Mage\Install\Model\Installer\Db.php
       D:\pro\ol.mce\app\code\local\ (local оставить, для подобных трюков)


В конце появится сообщение

You're All Set!
Get ready to experience Open-Source eCommerce Evolved.
Before you continue to your store, please make a note of your encryption key
(Magento  uses it to ecrypt passwords, credit cards and more)

  63ed97d1e8e5df9e650ab54b91a40835 (comp: home)
  d0a40bb643d004f3dafa1556c11b5494 (comp: work)
  8201c5f7eb25f978670808931f180990 (comp: work87)


(Make sure you keep it in a safe place.)



есть ещё инструкция D:\install\xampp\magento\ol_instruction\instuction_installation.txt
объединить после следующей исталяции
